### ISSUE TITLE
Doesn't work on Oreo with Magisk and Xposed

### ISSUE THREAD

**Issue by beppe9000** [ViRb3/TrustMeAlready#5]

**Comment by jpstotz** [comment]
If TrustMeAlready works depends more on the app and not the Android version. Therefore you have to exactly name the app where it does not work.

**Comment by beppe9000** [comment]
i tried a  bunch of apps, among them opera browser, stock browser. After some digging I'm not sure if it's this or the PC side...

**Comment by jpstotz** [comment]
TrustMeAlready uses Xposed therefore it only can modify the part of the app that has been implemented in  Java/dex code. 
Web browsers are mostly written in C/C++ or other languages that compile to native code (ARMv7/ARMv8, ...). Those parts can not be modified using Xposed. 

If you want to do so you have to use Frida.

**Comment by ViRb3** [comment]
As suggested by the [Troubleshooting](https://github.com/ViRb3/TrustMeAlready#troubleshooting) section, try sniffing Google Chrome's traffic. Last time I tried it worked, so you can use it as a benchmark.

**Comment by beppe9000** [comment]
I recompiled the app and the problem solved itself. Indeed I can see all other apps traffic too.

**Comment by ViRb3** [comment]
Did you recompile TrustMeAlready or your target app?

**Comment by beppe9000** [comment]
The target app... it's bizarre.

**Comment by ViRb3** [comment]
Interesting. I think what solved was something else, but glad it got sorted out either way :)

**Comment by beppe9000** [comment]
Yeah I do too. I dump some detail here: I am using the magisk module that copies CA certificates to system store with the one generated by fidler 5 but they would not be trusted. I recompiled the app to a lower api version, reinstalled using lucky patcher, rebooted and boom everything works from every app.
