### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by 89z** [ViRb3/TrustMeAlready#7]
I am using Android 8, so based on this:

https://github.com/ViRb3/TrustMeAlready#requirements

I went here:

https://forum.xda-developers.com/showthread.php?t=3034811

Then I went to this page:

https://dl-xda.xposed.info/framework/sdk26/x86

I have downloaded and extracted the Zip file, but what do I do now? How do I install this?

**Comment by 89z** [comment]
Magisk doesnt work with Android Studio:

https://android.stackexchange.com/questions/242246/magisk-v23-with-android-studio

**Comment by rob-X1** [comment]
@89z Not sure what you want to say by your last post. Magisk is an on-device rooting solution and Android Studio is an PC based Android app development IDE. 
Both have nothing in common, so your post sounds to me like "oranges don't work with pears" (a sentence that does not make sense at all just like your post).

**Comment by 89z** [comment]
I guess youve never heard of Android Virtual Device?

https://developer.android.com/studio/run/managing-avds

**Comment by rob-X1** [comment]
That is the Android Emulator, not Android Studio. The emulator is part of the Android SDK which can be downloaded separately.

Google has removed the stand-alone GUI for managing the emulator, so that the emulator is now a command-line application. That and the fact that Android SDK and Android Studio is usually downloaded together might lead to the false interpretation that the emulator is part of Android Studio but it isn't.

**Comment by 89z** [comment]
Dude, I dont know what the hell you are talking about.

I downloaded this [1]. When I start it up, I choose More Actions, AVD Manager. So before you talking any more nonsense, maybe you should actually visit the link I have below, and actually test what I have said.

1. https://developer.android.com/studio

**Comment by 89z** [comment]
I downloaded this [1]. When I start it up, I choose More Actions, AVD Manager. I have gone ahead and blocked @rob-X1. Since in my mind, he is just trolling at this point, rather than trying to actually help.

1. https://developer.android.com/studio

**Comment by ViRb3** [comment]
There was absolutely no trolling in @rob-X1's first comment. The Xposed SDK you linked is used to **develop** Xposed modules like this one. You load the Xposed SDK in Android Studio and you write code that can later be ran by Xposed-compatible frameworks.

What I assume you want to do is run the already built version of TrustMeAlready. For that, you need to install an Xposed-compatible framework like EdXposed, not any of their SDKs. Again, this was well answered by @rob-X1. I cannot help more beyond that.

The rest of the comments are out of context, I suppose they were related to some now-deleted comments. Either way, I can see nothing wrong here, and the initial question was answered. Closing this issue.
