### ISSUE TITLE
Add LSPosed support

### ISSUE THREAD

**Issue by iAvoe** [ViRb3/TrustMeAlready#8]
Hi, please add support to LSPosed (Android 10~12).
Thanks!

**Comment by rob-X1** [comment]
From https://github.com/LSPosed/LSPosed
> Module written based on LSPosed framework is fully compatible with the original Xposed Framework, so contrary a Xposed Framework-based module will work well with the LSPosed framework too.

In my understanding this means any Xposed module is compatible with LSPosed. So I don't understand what you are asking for.

**Comment by yoshimo** [comment]
Maybe the Problem is a specific App that implements pinning a different way and/or #2 & #3

**Comment by sokcuri** [comment]
Maybe it's talking about making the list appear in the LSPosed repository.

**Comment by ViRb3** [comment]
This module should definitely work with LSPosed. If it does not, please provide a little more detail. Note that as mentioned above, some apps use custom certificate pinning methods and this module will not work on them. This is not a bug, though.

I don't have any plans to add it to the LSPosed repository at the moment, but you can always download it from here.
